### ISSUE TITLE
Recurring code pattern #2: iterator.return()

### ISSUE THREAD

**Issue by KSXGitHub** [sithmel/iter-tools#150]
This issue is not about `iterator.return()`, but rather, the `try ... while (true) ... finally ...` pattern that appears in many places.

For reference, I tried https://github.com/sithmel/iter-tools/pull/129 for `partition`.

**Comment by sithmel** [comment]
I didn't find many places where this is used. Also I would avoid obfuscate the code with a function call, if it is not really worth it

**Comment by KSXGitHub** [comment]
> Also I would avoid obfuscate the code with a function call, if it is not really worth it

I see it as a separation of concerns. When this pattern appears in a place, the need to test it arises (or to fill test coverage so to speak). The more places this pattern is used, the more tests we need to write. Right now, we don't even test if `partition` calls `iterator.return()` correctly! So I propose the wrap this pattern in a module, we then only need to test that module, once.

**Comment by KSXGitHub** [comment]
BTW, that's how functional programming works: Instead of writing a huge monolithic function which is impossibly hard to test, programmer writes multiple small testable function and compose them together.

**Comment by conartist6** [comment]
I agree with @sithmel here. Even if there is some small penalty to pay in library size for having a syntax that's repeated many places, there's also a big penalty to pay for replacing parts of your code that have the same meaning to everyone with custom function calls and syntaxes that could mean anything unless you make a separate trip to look up their implementation. Obviously if there is any bigger chunk of functionality needed multiple places, especially as you mentioned bits that can be documented (with comments) and tested as independent logically complete units, even if they are only used internally.

@KSXGitHub I suspect that you have yet to work in the kind of codebase that would give you an appreciation for just how crazy you can start going when people travel down the path of making a domain specific language in which their code is written, instead of trying to figure out how best to use the language that everyone knows to express what they mean.
