### ISSUE TITLE
Suggestion: Function that turns an iterator into an iterable that lasts forever.

### ISSUE THREAD

**Issue by KSXGitHub** [sithmel/iter-tools#184]
## Usage

```javascript
const iterator = range(4)
const iterable = everlasting(iterator)
Array.from(iterable) // [0, 1, 2, 3]
Array.from(iterable) // [0, 1, 2, 3]
Array.from(iterator) // []
Array.from(iterable) // [0, 1, 2, 3]
```

```javascript
let count = 0

function * generator () {
  yield count++
  yield count++
  yield count++
}

const iterator = generator()
const iterable = everlasting(iterator)

count // 0
Array.from(count) // [0, 1, 2]
count // 3
```

## Features

* The returning iterable (`iterable`) is lazy, i.e. input iterable (`iterator`) won't be consumed until the returning iterable is consumed for the first time. 
* After fully exhausted for the first time, it still emits elements (from an internal cache).

## Suggestion

Either:
1. Change existing `iterable` and `asyncIterable` functions
2. Create new functions

### Why not `Array.from`, `toArray`, `asyncToArray`? [ref](https://github.com/sithmel/iter-tools/issues/184#issuecomment-460044040)

Arrays are not lazy.

### Why not `tee`/`fork`? [ref](https://github.com/sithmel/iter-tools/issues/184#issuecomment-460066430)

It is too verbose.

I would rather not have `tee`/`fork` as `everlasting` can do what `tee`/`fork` can do and more:
  * `everlasting` can clone itself, that's what `tee`/`fork` can do.
  * `everlasting`'s usage is simpler, that's what `tee`/`fork` can't do.
  * `everlasting`'s implementation is simpler, that's what `tee`/`fork` refused to do.

**Comment by sithmel** [comment]
I am puzzled by this.
Iterable seems to be an array

**Comment by KSXGitHub** [comment]
> Iterable seems to be an array

Arrays are not lazy, and there's no "async" array.

**Comment by conartist6** [comment]
Yeah I agree. Just use `Array.from` to make an array. If you need it to be lazy, use `fork` like this:
```js
const iterator = range(4)
const forkIterator = everlasting(iterator)
Array.from(forkIterator.next()) // [0, 1, 2, 3]
Array.from(forkIterator.next()) // [0, 1, 2, 3]
Array.from(iterator) // []
Array.from(forkIterator.next()) // [0, 1, 2, 3]
```

**Comment by sithmel** [comment]
> Arrays are not lazy, and there's no "async" array.

If you need to replay an iterator, there is no other way than caching the values yielded the first time.
You can do that either by
* consuming it with toArray or asyncToArray and then using the array
* use fork/asyncFork

```js
for (const iterable of fork(range(4)) {
  // in here you get infinite copies of range(4)
}
```
or
```js
for (const iterable of asyncFork(whatever)) {
  // in here you get infinite copies of whatever
}
```

**Comment by KSXGitHub** [comment]
@conartist6 

> Yeah I agree. Just use `Array.from` to make an array. If you need it to be lazy, use `fork` like this:
> 
> ```js
> const iterator = range(4)
> const forkIterator = everlasting(iterator)
> Array.from(forkIterator.next()) // [0, 1, 2, 3]
> Array.from(forkIterator.next()) // [0, 1, 2, 3]
> Array.from(iterator) // []
> Array.from(forkIterator.next()) // [0, 1, 2, 3]
> ```

You meant `Array.from(forkIterator.next().value)`? Quite verbose, isn't it. If I have to choose between `fork` and `everlasting`, I would prefer `everlasting` as it has more elegant usage and simpler implementation.

As for @sithmel's [comment](https://github.com/sithmel/iter-tools/issues/184#issuecomment-460084246), I say the same, except the code blocks: Using loop for this seems like an anti-pattern to me, beside, I may want to pass "everlasting" iterable to other places (other functions, etc.).

I have updated my original comment BTW.

**Comment by conartist6** [comment]
Uh, and what is that implementation?

**Comment by KSXGitHub** [comment]
> Uh, and what is that implementation?

IIRC, `fork` needs dedicated classes, correct? `everlasting` only needs an array as cache.

**Comment by conartist6** [comment]
Fork just has a cache. Doesn't matter what the cache is. My version had an array in some cases. If you want something simpler than a cache I don't know what that might be.

**Comment by KSXGitHub** [comment]
> Fork just has a cache. Doesn't matter what the cache is.

That cache requires a class that is written in a file (`/src/internal/queues`) that contains more classes which requires more code. On the web, the smaller the file, the better. When tree-shaking is at work, if I only use `everlasting`, my bundle should contain only a few lines of code, unlike `fork`.

**Comment by sithmel** [comment]
@KSXGitHub it is much clearer now
Everlasting is a really confusing name. What about "cachedIterable" or "toLazyArray"?

Anyway "fork" does already that, the queues.mjs file can be minified in around 1KB (Probably 700/600 bytes when compressed through http) and it is faster to consume than an array (I measured it with the test suite).
```js
const [clone1, clone2, cloneN] = fork(range(4)
```
just use the clones, each one of them behaves like you want. They are super light as they share the same queue instance

Also they are more memory friendly than a "lazyArray". As soon as you start consuming the last one, the memory gets freed immediately.

**Comment by KSXGitHub** [comment]
> We would create a disservice to the developers (and to our future selves) adding a slightly optimised version of something we already have: more things to remember, more stuff to download from npm, more to maintain.

It is not necessary a new function, we can change existing `iterable`.

> regenerator runtime

You're assuming that I transpile all my code.

**Comment by KSXGitHub** [comment]
Forgot to add,

> Fork is a bit bigger than necessary for your case, but it covers it pretty well.

From my point of view, it is not, as my use case is one variable to rule them all.

Anyway, are there any other use case that `fork` is used for but `everlasting` can't do.

**Comment by conartist6** [comment]
> Are there any other use case that fork is used for but everlasting can't do?

Calling `return` on the source iterable

**Comment by sithmel** [comment]
> Anyway, since you said "bigger", are there any other use case that fork is used for but everlasting can't do?

The ideal use case for "fork" is to carry on operations in parallel. For example something like this:
```js
const doubleAndSquare = pipe(
  fork,
  mapFunc([map(double), map(square)]), // here I am again with mapFunc :-)
  zip
)
for (const [double, square] of doubleAndSquare(range(1000000000))) {
  console.log(double, square)
}
```
In this example **fork** generates 2 cached clones, but they are consumed at the same time, so the memory is not exhausted.

Given the length of the sequence, a simple caching will fill up the memory.

**Comment by conartist6** [comment]
@KSXGitHub I think you have a fundamental misunderstanding.`return` is pretty important. First, since you mentioned it, `return` is not called when an iterable is exhausted. Iterables can return two ways. They can inform their consumer that they have run out of items, in which case they initiate any required cleanup, or their consumers can inform them that they no longer intend to consume any more items, in which case `return` is called to give the iterator a chance to do its cleanup.

The thing is, in order to know that it is safe to call `return` on the source, you must know for sure that you will not need any more of it. Your proposed method could not possibly know that, because at any time someone could call `Symbol.iterator` and the method would need to produce an iterator capable of iterating all the way to the end of the source. This doesn't matter if the iterable is exhausted completely, which is the only case you seem to be considering. It does matter if the iterable is not exhausted, such as because somebody called `slice()` on it.

Now sometimes this might not matter, because ultimately the garbage collector will come around and clean up the whole thing, but sometimes there is more going on than memory. Consider the following iterable:

```js
function * readLinesFromFile(file) {
   const fileDescriptor = fs.openSync(file)
   try {
     ...
   } finally {
     fs.closeSync(fileDescriptor)
   }
}
```

Lets say you used this function and called `slice` on it in order to implement something like the [head](https://linux.die.net/man/1/head) command. If you were to call everlasting here, you would leak a file handle. This is just one instance of code doing something that requires cleaning up. Another might be registering an event listener (which would even prevent the GC from helping). It is not worth, creating all these largely invisible problems just to simplify the API a bit. The simple API would not be simpler when it would need to be attached to a lengthy documentation of disclaimers documenting all the situations in which it would be unsafe.

And finally, I repeat: most of the time what you want will simply be accomplished by calling `Array.from(iterable)`

**Comment by KSXGitHub** [comment]
@conartist6 Welp, you opened my eyes.

**Comment by conartist6** [comment]
Haha glad I could help. It's complicated, and I don't think any of us understood it properly before we started writing code in this repo (and discovering the ways in which it was incorrect)

**Comment by sithmel** [comment]
> I don't think any of us understood it properly before we started writing code in this repo

I confirm. I even opened a ticket in other repo and they are still puzzled about this https://github.com/bustle/streaming-iterables/issues/22
