### ISSUE TITLE
Consistency: call patterns and composability

### ISSUE THREAD

**Issue by sithmel** [sithmel/iter-tools#185]
I am picking up from #170 where the issue of consistency was raised. I'll try to classify the functions by calling arguments/return value. I am not listing all functions. But I think they are enough for a couple of observation and a proposal:

#### Fixed number of arguments, ended by an iterable/asyncIterable. Returns an iterable/asyncIterable:
* batch
* asyncBuffer
* cursor
* dropWhile
* flatMap
* flat
* interpose
* groupBy
* slice
* takeWhile
* tap
* asyncThrottle
* map
* filter

I like this calling pattern  It is simple enough and it enable function composition (using pipe or compose).

#### Fixed number of arguments, ended by an iterable/asyncIterable. Returns a value:
* every
* find
* some
* size
* consume ( returns undefined)

This is very similar to the one above. 

#### Fixed number of arguments, ended by an iterable/asyncIterable. Returns an iterable of iterables:
* partition
* fork
* splitBy (work in progress)
* splitAt (work in progress)

This is emerging recently. It enables to work with multiple slices (of clones) of the same iterable

#### Dynamic number of arguments
* asyncFilter
* asyncMap
* takeSorted 
* reduce (return a value)

For these I have a proposal. I am writing a curry that is based on the last argument (if it is an iterable it stops currying). This should sort these and the first list.

#### multiple iterables. return a single iterable
* concat
* compress
* zipAll
* zip
* merge/collate

For these I have a proposal. Given that we have a few functions returning iterable of iterables, it would ease function composition if these function would take an iterable of iterables as argument.

**Comment by conartist6** [comment]
I can see the theoretical elegance of changing the functions which take multiple iterables to take an iterable of iterables, but it seems a bit like sacrificing the common use case for the benefit of the uncommon one.

**Comment by KSXGitHub** [comment]
> I can see the theoretical elegance of changing the functions which take multiple iterables to take an iterable of iterables

Elegance in implementation, but not in usage.

> but it seems a bit like sacrificing the common use case for the benefit of the uncommon one.

I agree with this.

**Comment by sithmel** [comment]
> I can see the theoretical ..

> .. like sacrificing the common use case for the benefit of the uncommon one ...

This is not theoretical or uncommon, this is how I write data pipelines!
I can also argue that this should be the preferred method.

Read this:
```js
const doubleAndSquare = (iterable) => {
  const [fork1, fork2] = fork(iterable)
  const doubles = map((x) => x * 2, fork1)
  const squares = map((x) => x * x, fork2)
  return zip(doubles, squares)
}

for (const [double, square] of doubleAndSquare(range(1000000000))) {
  console.log(double, square)
}
```
I find this less readable because the iterable is changing name as it gets transformed.
It is also error prone, because you may do a mistake passing down the right iterable. For example:
```js
  ...
  const doubles = map((x) => x * 2, fork1)
  const squares = map((x) => x * x, fork1) // ops typo
  ...
```
And this doesn't make sense because you *never* want to pass the same iterable to 2 different functions, because a transformation will consume the iterable.

This is the functional alternative.
```js
const doubleAndSquare = pipe(
  fork
  mapFunc([map((x) => x * 2)], map((x) => x * x]),
  zip
)

for (const [double, square] of doubleAndSquare(range(1000000000))) {
  console.log(double, square)
}
```

**Comment by sithmel** [comment]
Another problem is that makes impossible to keep consistence. For example the following 2 are inconsistent:
```js
zip(iter1, iter2) // I get 2 iterables
collate(func, [iter1, iter2]) // I get an array of iterables
```

**Comment by sithmel** [comment]
@KSXGitHub edited

**Comment by conartist6** [comment]
@sithmel If we add the optional parameter back to fork back you could at least have:
```js
const doubleAndSquare = (iterable) => {
  const forks = fork(iterable, 2)
  const doubles = map(x => x * 2, forks.next())
  const squares = map(x => x * x, forks.next())
  return zip(doubles, squares)
}
```
It alleviates your valid concern about a subtle naming mixup, which is particularly likely when the user is forced to pick two different names for what is still essentially the same thing. I would say that after thinking about this use case, I now strongly support that.

I still think that this idea parallelism in data processing is best expressed as code which is written in columns is not robust, and I am particularly unhappy about the idea of making sacrifices from our most basic use cases, which I imagine to have at least 20 times more potential audience than code-in-columns data pipelines. It is because I believe that this library is currently only reaching a tiny fraction of the programmers who it should interest that I have invested time and effort in it. It is at present a bit of a conflict between my interest in serving that yet-unrealized constituency and your interest in refining your existing use cases.

Luckily I think that we can both have pretty much exactly what we want here. Here are some that I can think of:

Exploit the fact that functions are objects, and choose a consistent naming scheme. For example you could have `zip.items` and `collate.items`, each of which would be defined to be a variant of the function which accepted an iterable of iterables. The hardest part of that would just be getting the typedefs right, and even that isn't too hard.

Alternatively, you could make a helper function based on your `currying` helper function, which would turn a method from varargs to iterable-of-iterables style. Usage might look like `collectParams(zip)`. I cannot think of any reason a correct implementation would not be possible.

Do either of these ideas seem reasonable to you?

**Comment by sithmel** [comment]
To manage *zip* I can do this:
```js
const doubleAndSquare = pipe(
  fork,
  mapFunc([map((x) => x * 2), map((x) => x * x]),
  ([arg1, arg2]) => zip([args1, args2])
)
```
It is not beautiful but I can live with that.
Or either one of the solutions above is also ok.

However, this **doesn't** solve the inconsistency in methods like *collate* when you have both iterables **AND** extra arguments

**Comment by sithmel** [comment]
On a different topic. I am still working on a variadicCurry function that will simplify a lot our code (looking forward to show you!). I want to ask your opinion:
Given that the iterable (or asyncIterable) is always going to be mandatory and it will be the rightmost argument. Where should I place mandatory and optional arguments ?

### Option 1:
```js
function test(optional1 = 1, optional2 = 2, mandatory, iterable) {...}
```

**or**

### Option 2:
```js
function test(mandatory, optional1 = 1, optional2 = 2, iterable) {...}
```

and why?

**Comment by conartist6** [comment]
You can make that just `(...args) => zip(args)`.

What's do you consider to be the inconsistency? The pattern of some fixed arguments followed by some variable ones is at least as old as C (I'm thinking `printf`) and is even formalized for javascript in es6. And I don't think there's any issue from the perspective of the currying helper. Anything before the first iterable is configuration, anything after the first iterable arg is data. You should be allowed to partially apply the configuration, in which case the next call will be data arguments.

My rule is to put the arguments in the order in which they are most important to understanding how the complete expression behaves. I would say that Options 2 is correct though, since the language specification dictates that non-optional parameters may not follow optional ones.

**Comment by sithmel** [comment]
```(args) => zip(...args)``` rather. But I got the point ;-)

> the language specification dictates that non-optional parameters may not follow optional ones

what specs ? I tried both way and it worked ok.

**Comment by conartist6** [comment]
Oh right, sorry, javascript is ok with it, it's typescript that won't allow a non-optional type parameter after an optional one.
```ts
declare function test(opt?: boolean, required: boolean)
```

**Comment by sithmel** [comment]
@KSXGitHub what form do you prefer and why ? ^^^

**Comment by KSXGitHub** [comment]
From TypeScript perspective, both options have optional arguments preceding mandatory ones and require multiple overloading declarations either way. 

But from JavaScript perspective, option 1 is more consistent: All mandatory arguments are placed after optional ones. 

```javascript
function test (opt1, opt2, mandatory, ...iterables)
```

**Comment by sithmel** [comment]
I lean for *option 1* for the same reasons of @KSXGitHub but I don't feel particularly strong about that.
@conartist6 is it ok for you if you stick to *option 1*?

If not I am happy to discuss :-)

**Comment by conartist6** [comment]
So the functions with optional parameters are:
- `collate(skipOrComparator?, iter)`,
- `reduce(initialValue?, callback, iterable)`
- `asyncFilter(concurrency?, callback, iterable)` (and `asyncMap`)
- `fork(count, iterable)` (potentially)
- `takeSorted(???, iterable)` (the documentation does not specify where that parameter goes)

**Comment by sithmel** [comment]
> `takeSorted(???, iterable)` (the documentation does not specify where that parameter goes)

```takeSorted(number, comparator?, iterable)```

^^^ this is the odd one

**Comment by sithmel** [comment]
I am working on "option 1" please shout if we need further discussion @conartist6

**Comment by sithmel** [comment]
The following functions follow the opposite convention. They take the iterable as a first argument and optional arguments afterwards:
* combinationsWithReplacement
* combinations
* enumerate.asyncEnumerate
* permutations
* repeat

Now, I understand they don't lend themselves particularly to use curry.
But forces developers to remember to use a different calling pattern.

I propose to make them follow the same convention as any other function.

**Comment by KSXGitHub** [comment]
@sithmel `repeat` does not take iterable as argument

**Comment by sithmel** [comment]
The discussion is now carried over on #201 #202
