### ISSUE TITLE
undefined should not be a valid iterable

### ISSUE THREAD

**Issue by sithmel** [sithmel/iter-tools#188]
In iter-tools we supported using as iterable null and undefined (both returning a sequence of 0 length).

In hindsight allowing undefined was a mistake. Two main reasons:

* it is an horrible way to swallow bugs
* undefined can be used for optional fields and interfere with the work for bringing consistency to all functions

**Comment by conartist6** [comment]
As I said on the PR, I disagree strongly. A huge part of the benefit of using function utilities is that they work regardless of whether the value exists. This is not swallowing a bug, it is understanding that the code can be interpreted as written, and not creating a whole category of needless errors many of which are sure to be passed on to users of the software.

If some of our functions with trickier signatures still need custom currying logic in order to preserve behavior around undefined, that is a burden that we should be happy to bear in order to prevent a whole class of needless errors in code that uses iter-tools methods. It isn't the most elegant code that usually adds the most value, its the uglier code that saves anyone else from having to deal with the ugly shape of the problem.

**Comment by conartist6** [comment]
I mean, just a core part of why iter-tools should be use widely is that you can do something like this without worrying if it's an error:
```js
map(val => val.toString(), myObj.undef)
```
Why should we demand that the user complicate this code? They'd have to write:
```js
map(val => val.toString(), myObj.undef || null)
```
but actually that's not really right at all because of 0 and false which should not be valid iterables, instead what really they should be writing *everywhere* in order to protect themselves is:
```js
map(val => val.toString(), myObj.undef === undefined ? null : myObj.undef)
// but likely that will be truncated to
map(val => val.toString(), myObj.undef == null ? null : myObj.undef)
```
And all of this gets even more needlessly complicated if you were doing something more like `getObj().undef`. Now what was a one line expression needs to be two lines to be correct, and most programmers are simply lazier than that.

**Comment by conartist6** [comment]
I guarantee you though `|| null` is what will actually be written many places, which obscures real bugs and potentially creates incorrect runtime behavior

**Comment by conartist6** [comment]
If we recommend the long form with `=== undefined` coders will shorten it to `== undefined` and then someone will see that and shorten it to `== null` and someone will see `myObj.undef == null ? null : myObj.undef` and they'll think that it must a no-op and remove it from the code and the code will still work for the moment because they won't happen to run a case where the value was undefined until even later on when something somewhere changes silently from returning undefined to null because the programmer didn't notice or care the difference and didn't think it could cause breakage far away in their code.

If you haven't noticed, I'm **really** against this one.

**Comment by sithmel** [comment]
I see your point. It really boils down to how irregular are the API and libraries out there.

I double checked the interaction with the curry. Let's use groupBy as an example.
The logic is:
* last argument must be an iterable
* from 1 to 2 arguments.

Without curry:
```js
groupBy(optionalFunction, iterable); // works
groupBy(iterable); // last argument iterable
groupBy(optionalFunction, undefined); // works
groupBy(undefined); // last argument iterable
```
No problem so far.

With curry:
```js
groupBy(optionalFunction)(iterable); // works
groupBy(optionalFunction); // last argument iterable

groupBy(undefined, iterable); // doesn't work
groupBy(undefined, undefined); // doesn't work
```
So basically we can set a rule that if an argument is optional, should never be passed undefined.

That's good enough for me. I am amending the PR

**Comment by sithmel** [comment]
If this sounds acceptable I would close the issue

**Comment by conartist6** [comment]
I'm fine with that
