### ISSUE TITLE
Why do splitAt and syncSplitAt return iterators and not arrays?

### ISSUE THREAD

**Issue by KSXGitHub** [sithmel/iter-tools#194]
In [recent PR](https://github.com/sithmel/iter-tools/pull/190) made by @conartist6, `splitAt` and `asyncSplitAt` were changed to return iterators. So I ask: _What is the reason for this? Why can't they create arrays directly?_

I created this issue because arrays are slightly more useful than iterators when we deal with tuples in TypeScript. For instance:

```typescript
const tuple: [number, number, string] = [0, 1, 'a']
const [a, b] = splitAt(2, tuple)
type A = typeof a // IterableIterator<number>
type B = typeof b // IterableIterator<string>
```

**Related:** https://github.com/sithmel/iter-tools/issues/192

**Comment by conartist6** [comment]
For the same reason as we do it with fork. If someone writes `const [first] = splitAt(3, iterable)` we want to understand that we're ready to call return on iterable after the first three items have been read. If you take the second half (`const [, second] = splitAt(3)`) I think that's fine because the second half will cache the first half and then that second iterable, when returned, will return the first, and if exhausted has also exhausted the first.

**Comment by KSXGitHub** [comment]
Then this is resolved.
