### ISSUE TITLE
Unclear magic using "return"

### ISSUE THREAD

**Issue by sithmel** [sithmel/iter-tools#42]
I got a bit confused following the explanation in http://exploringjs.com/es6/ch_iteration.html#_closing-iterators-via-return

The issue is related to the functions taking as input an iterable and returning an iterable: map, filter, slice and many others.

When you stop consuming one of the iterables returned by those, you can call "return", as specified in the link above (or rely on for..of that is going to do that automatically).
The problem is that I don't see how we are able to close the previous iterable calling return on that.

I wrote this bit of code to verify my doubt:
```js
const slice = require('./es2018/slice')

const inf = {
  next: () => ({ done: false, value: 'x' }),
  return: () => { // who is calling this ?
    console.log('close')
    return { done: true }
  }
}
 
const iter = {
  [Symbol.iterator]: () => inf
}

for (const i of slice(3, iter)) {
  console.log(i)
  break // this should fire "return" on the generator object created by slice
}

// x
// close
```
The good news is that, despite my concern it works fine (it calls return) I didn't understand how this magic works though.

**Comment by conartist6** [comment]
No magic. Inside the `slice` implementation, you're using `break` in a `for..of` loop, which is one of the native constructs that calls return.

**Comment by sithmel** [comment]
sorry, I realised my example didn't prove my point. So I updated it

**Comment by conartist6** [comment]
I think what you're curious about must be an implementation detail of generator functions. I don't see documentation of it, yet clearly it makes sense and works: a `for..of` is terminated and given a chance to terminate its iterator if it is inside a generator function whose execution has been halted with return.

The thing I don't know is: if you weren't using `for..of` but instead doing custom iteration inside a generator function you'd still want to clean up by calling your source iterator's `return` when the generator's `return` method was called, and I don't know how you'd do that. This seems like it could already be an implementation bug in `zipLongest`, which though it exhausts all iterators when it is itself is exhausted, does not when its execution is aborted with `break` or similar. It sort of seems like perhaps you just shouldn't use generator functions for that, that a utility function which uses custom iteration must itself be a custom iterator implementation in order to be completely correct.

**Comment by sithmel** [comment]
I can confirm your suspect. This test fails:
```js
  it.skip('closes when stopping earlier', function () {
    let calledClose = false
    const repeatX = {
      next: () => ({ done: false, value: 'x' }),
      return: () => {
        calledClose = true
        return { done: true }
      }
    }

    const iter = slice(2, zipLongest(range(2), {[Symbol.iterator]: () => repeatX}))
    expect(Array.from(iter)).toEqual([[0, 'x'], [1, 'x']])
    expect(calledClose).toBe(true)
  })
```

Also I thought to have fixed zip:
```js
import ensureIterable from './internal/ensure-iterable'

function closeIterators (iters, except) {
  let c = 0
  for (const iter of iters) {
    if (c === except) {
      c++
      continue
    }
    if (typeof iter.return === 'function') iter.return()
    c++
  }
}

export default function * zip (...iterables) {
  const iters = iterables.map(i => ensureIterable(i)[Symbol.iterator]())
  while (true) {
    const zipped = new Array(iterables.length)
    let i = 0
    let c = 0
    for (const iter of iters) {
      const {done, value} = iter.next()
      if (done) {
        closeIterators(iters, c) // clean up unfinished iterators
        return
      }
      c++
      zipped[i++] = value
    }
    yield zipped
  }
}
```
This works in this test case:
```js
  it('closes when stopping earlier', function () {
    let calledClose = false
    const repeatX = {
      next: () => ({ done: false, value: 'x' }),
      return: () => {
        calledClose = true
        return { done: true }
      }
    }

    const iter = zip(range(2), {[Symbol.iterator]: () => repeatX})
    expect(Array.from(iter)).toEqual([[0, 'x'], [1, 'x']])
    expect(calledClose).toBe(true)
  })
```
But it doesn't work in this case:
```js
  it.skip('closes when stopping earlier, using slice', function () {
    let calledClose = false
    const repeatX = {
      next: () => ({ done: false, value: 'x' }),
      return: () => {
        calledClose = true
        return { done: true }
      }
    }

    const iter = slice(1, zip(range(2), {[Symbol.iterator]: () => repeatX}))
    expect(Array.from(iter)).toEqual([[0, 'x']])
    expect(calledClose).toBe(true)
  })
})
```
I would like to know exactly the magic behind "return" and "for..of", so we can address this.
I'll try to have a look in the next days.

**Comment by sithmel** [comment]
Still not 100% clear. But based on my tests, this is what I think happens:

If you use a for..of, your generator function automatically gets a "finally" clause that provides includes a "return" call.

What you have in the "finally" clause of a generator function is automatically called with "return" in the generator object.

I tested this approach successfully. This translates in the rule:

```
whenever your function uses a generator object outside a for .. of loop, you must add a "finally" clause for closing all generator objects with "return"
```

On a sad note, babel fail on this. So I had to skip the tests.

**Comment by conartist6** [comment]
Oops, mistake, sorry.

**Comment by conartist6** [comment]
I've figured out what's going on with Babel failing. It was unpleasantly difficult. The problem is with slice, not with zip. Long story short, there's a limitation in `transform-regenerator`. That limitation is described here: http://babeljs.io/docs/en/babel-plugin-transform-es2015-for-of/#options-loose. We have the loose option enabled:
```
      "presets": [
        ["@babel/preset-env", {
          "loose": true
        }]
      ]
```

Turning that option off unbreaks this test case at the cost of performance in the `es5` code. I'd say we have no choice, the library code is only correct with strict on.

**Comment by conartist6** [comment]
By the way, here's a really easy way to play with it -- you can control strict under the `env-preset` accordion tab on the left.

https://babeljs.io/en/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=true&code_lz=GYVwdgxgLglg9mABAKkQZxgWwA4BsCmAyrjBPogBT5gAmANIjFPgE4CGARgQJSIDeAKESICURBBAsW1KAAU4aRAF5EABgDcQxMDgtKEBGjFN8mRHGCNm7Lvl6DhwmJYoSpM-YoB8K6jXtajogc0mwA1oGIAL6RAJ4w-Lg0VqaRbtJgcgoA1NlaMTECBmBGiNLY-GxQABrK_Fpg-AAeUABclLxKXpR8iDQI-O3AbLho-AwAbiMgg4gA5E1z0dx0WtJQkmBD4NDwYBT2iCOsUBRzHLphc7xRq8IA2oSxmBe4AHQm7FC6ALoH_GV8BsWEgoAALGCKAoCAQAQSkbFib2ALDgmAoGBwBGIpHwFAAjAxypUatxuEA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&sourceType=module&lineWrap=true&presets=es2015%2Ces2016%2Ces2017%2Cenv&prettier=false&targets=&version=6.26.0&envVersion=1.6.2

**Comment by conartist6** [comment]
I like what you did with `try..finally` though. I was working on my own solution involving custom iterators and this is way simpler and easier to read/understand.

**Comment by conartist6** [comment]
Also TIL that you can write `return yield* ...`.
