### ISSUE TITLE
[Typescript] externalise type definitions

### ISSUE THREAD

**Issue by sithmel** [sithmel/iter-tools#65]
The intention of this tickets is to discuss the possibility to take away the TS definitions from this package and move them elsewhere.

The reason is that changes to the definitions is leading to multiple releases, not really useful for the ordinary js user.

Also that would help distributing the responsibility of maintaining these two packages.

Any ideas ?

**Comment by KSXGitHub** [comment]
I suppose `iter-tools`'s type definitions used to be in `@types/iter-tools` package (I can't find in npm site now). Now I think [`@types/iter-tools`](https://github.com/DefinitelyTyped/DefinitelyTyped) is the perfect place to contains the type definition. There're pros and cons IMO:

* **Pros:**
  - People at DefinitelyTyped are knowledgeable of TypeScript.
  - Responsibility is distributed.

* **Cons:** DefinitelyTyped is a **big** monorepo that contains every type definition for almost every JavaScript module. It leads to a few limitation because of this.
  - Communication in DefinitelyTyped is awful: If one find a bug or an incorrect type or a way of improving types, they better make pull request because if they file an issue, nobody gonna notice them.
  - Automatic testing (Travis CI) is unpredictable due to memory bottleneck: It fails frequently, one must close and re-open pull request every time it fails.
  - It lacks the tools I needed to write/test my type definitions (from my pending pull requests that is): DefinielyTyped has 2 and only 2 dev dependencies: `dtslint` and `type-publisher`. If I want to move the definitions from my yet-to-be-merged pull request there, I must literally copy/paste everything from my libraries (`typescript-tuple`, `typescript-union`, `static-type-assert`, `typescript-logic`) to one file `types/iter-tools/index.d.ts`.

**Comment by KSXGitHub** [comment]
On the bright side, the [test](https://github.com/KSXGitHub/iter-tools/tree/pullrequest.improve-types/src/__spec__) I wrote is pretty straightforward, you can ensure if a type definition is correct by reading them (that is, if you trust [`static-type-assert`](https://github.com/ksxnodemodules/static-type-assert))

**Comment by KSXGitHub** [comment]
There's one point I forgot:

> The reason is that changes to the definitions is leading to multiple releases, not really useful for the ordinary js user.

I see in many package always release a bunch of "Release Candidate" versions (tagged `rc` and/or `next` instead of `latest`). They have a schedule in which they will release the latest release candidate after a period of time if they find no problem with it.
