### ISSUE TITLE
suggestion improve builds

### ISSUE THREAD

**Issue by hugomrdias** [sithmel/iter-tools#77]
the community is moving towards compiling dependencies so it's better to only run babel to transform esm to cjs and nothing else, and let the users of this package handle that with babel-preset-env.

This would look like this:
- point package.json main to cjs version (no transforms) basically the current es2018 
- point package.json module to src/index.mjs
- make a es5 standalone bundle for unpkg.com and point package.json unpkg to it

This covers most use cases node, browser with bundlers and script tag/prototype browser.

I'm currently developing a node/browser package,  i can work with iter-tools requiring directly the es2018 everywhere but that isn't optimal for browser tree-shaking with my proposal i would just do normal require `require('iter-tools) or require('iter-tools/map) const {map} = require('iter-tools)` or esm version of these and node/webpack/parcel/rollup would pickup the correct version for optimal output. Plus i could control the babel transform and ship less code to my users.

**Comment by hugomrdias** [comment]
i can submit a PR if you think this is useful

**Comment by sithmel** [comment]
Thanks for the feedback @hugomrdias, 
I am not 100% happy of how this is currently working, so I am very open to any suggestion.

Do you have any example on how a consumer of this package should be configured ?
Just for my understanding :-)

Also a PR would be amazing

**Comment by hugomrdias** [comment]
```json
{
  "main": "cjs/index",
  "module": "src/index"
}
```
with this in package.json

a package node/browser isomorphic or node consumer would just
```
const iter = require('iter-tools)
const { map } = require('iter-tools')
const map = require('iter-tools/map')
```
can defer responsibility to their own consumers because iter-tools supports this

a package browser consumer would just
```
import iter from 'iter-tools'
import { map } = from 'iter-tools'
import map from 'iter-tools/map'
```
can defer responsibility to their own consumers because iter-tools supports this

an app browser consumer would just
```
import iter from 'iter-tools'
import { map } = from 'iter-tools'
import map from 'iter-tools/map'
```
this consumer would have webpack compiling src + vendor with this babel config https://babeljs.io/docs/en/babel-preset-env#browserslist-integration and would target their own audience nothing else which translates in smaller bundles.

webpack picks up the module prop in iter-tools package json (https://webpack.js.org/configuration/resolve/#resolve-mainfields) and uses esm version which translates in treeshaking support.

**Comment by hugomrdias** [comment]
regarding builds iter-tools would only have ts->esm and esm to cjs (only with babel esm to cjs transform nothing else)

**Comment by sithmel** [comment]
@hugomrdias As far as I know, babel doesn't transpile the content of node_modules automatically. So the consumer needs to be aware of this and configure babel accordingly. Is it still true ?

**Comment by hugomrdias** [comment]
Babel transpiles what you tell it to transpile users need to config theirs bundle (webpack, roll-up etc) to run through src + node_modules

**Comment by conartist6** [comment]
I'm definitely interested, but not convinced yet. I think there's a lot to gain, in particular because the bundle size and expected performance for this library is so different when it runs using actual native generators vs the transpiled version. `create-react-app@2` now transpiles all deps using preset-env, so it would be OK. We'd still have to transpile the async generators since those are just a proposal and not supported in node or CRA deps (I think).

The biggest problem is that this module doesn't aim to be direct to consumer. Much of the time it will be used by some other library that the end user wants to use, and they might not even be directly aware that they're picking it up, which means that if we force any library which wants to use iter-tools to force their consumers to change the way they ship their code, we'd probably eliminate a lot of our potential user base.

I guess I don't see any potential drawbacks to publishing an extra npm module (`iter-tools-es`, say) built the way you describe, aside from some extra confusion as to which version people should use. Eventually when we see broad support we would be able to merge that behavior into a new major version of `iter-tools` proper and deprecate `iter-tools-es`.

**Comment by hugomrdias** [comment]
node 10 which is active LTS, CRA, babel-preset-env all support async iterators. 
each type of consumer still has the option to transpile whatever and distribute how they want, but a low level package like this already transpiling and adding size seems wrong.

right now any kind of developer that cares about size and perf needs to figure out all the builds iter-tools has, find the one that fits and probably do wierd requires like `require('iter-tools/es2018/map)` which isn't even in the repo its only generated for a npm release

**Comment by sithmel** [comment]
@hugomrdias Just to be sure to be on the same page. With 
```js
import { map } = from 'iter-tools/es2018'
```
you get the untranspiled source with treeshaking. You only have to add "/es2018". It is also explained in the [readme](https://github.com/sithmel/iter-tools#javascript-support).

You are proposing to get the same version using instead:
```js
import { map } = from 'iter-tools'
```

Did I get it right?

If this is the case we can just change the default. Instead of having es5 as a default we could have es2018.

**Comment by conartist6** [comment]
We could simply rename the es2018 folder to es. To me including a year number in your imports is a code smell. Then we'd have:
```js
import { map } from 'iter-tools/es';
```
es would simply denote that it was standard js, safe to transpile with `babel-env`. Of note is that `babel-env`'s "loose" options is *not* safe with iter-tools.

**Comment by sithmel** [comment]
not a fan of "es". es2018 is the name of the specs [es2018 specs](https://www.ecma-international.org/ecma-262/9.0/index.html). A dev should be able to know what version to use for what environment!

Another note. I picked up this old article from [Rich Harris](https://medium.com/@Rich_Harris/how-to-not-break-the-internet-with-this-one-weird-trick-e3e2d57fee28). He suggests that library authors should **bundle** their dependencies. Maybe it is not a bad idea after all. If I bundle my deps. And (for example) [sequins](https://github.com/conartist6/sequins) bundle theirs, there would be no need to rely on transpiled libraries.

The only transpilation would happen in the consumer project!

**Comment by conartist6** [comment]
Why should a dev need to know what version to use for what environment? The answer to that problem is probably completely intractable if the dev is coding a library (such as sequins (which bundles its own code but not its deps btw)) which doesn't know what the execution environment its consuming codebase will be. Because library authors can't know, they are forced to make the most conservative possible choice: es5. The current state of iter-tools reflects this. Most libraries have been stuck using es5 as a transpilation target even as they start using more and more language features which perform relatively poorly (and are way harder to debug) when transpiled down to es5 (e.g. generators) and are even in running in environments with sufficient es6 support. Thus I fully expect to see some trend to alleviate this problem, and have no trouble believing that create-react-app has set that trend in motion by making the decision to transpile `node_modules` with `babel-env`.

In terms of what you say about bundling, it sounds very much like you're advocating for the solution discussed above. "The only transpilation would happen in the consumer project," you say, which is exactly what we're talking about. Whether or not you bundle your deps is not really relevant to what language your bundle is in, and not relevant to the potential need to publish more than one version of the bundle in different language versions if different transpilation targets are to be supported. And other authors constructing their bundles which use your bundle still won't know which target version of their bundle they need. This solution degrades into everyone needing to publish complete bundles of their product in each transpilation target, with es5 bundles targeting dependent es5 bundles, and es6 bundles targeting dependent es6 bundles, and so on and so forth. It would be tremendously difficult to set up and maintain, and rather inefficient to boot.

**Comment by hugomrdias** [comment]
you kinda lost me here lol :) 

i did some more testing and es2018 seems to work for node and browser i didn't notice that it has .js and .mjs files, so node picks up .js and webpack .mjs and treeshaking works.

Still having to remember to use es2018 might be error prone because it isn't even on the repo.
one setup that works with normal requires is 

"main": "es2018",
"module": "src",

and .mjs can even be removed from es2018 and es2018 renamed to cjs, this would be 👍 

so to improve the proposal i would say

./cjs/* - would be cjs with no transpilation and serves `"main": "cjs"`for node
./src/* - its just what it is esm source code and serves `"module":"src"` for browser
./es5/* - would be the src transpiled to es5 and would serve devs that don't want to use babel-preset-env on node_modules

plus a optional standalone es5 bundle for script tags use cases

**Comment by sithmel** [comment]
I searched on google "webpack babel config" and these are the first 3 blog posts explaining how to configure webpack:
* https://www.valentinog.com/blog/webpack-tutorial/
* https://www.robinwieruch.de/minimal-react-webpack-babel-setup/
* https://hackernoon.com/a-tale-of-webpack-4-and-how-to-finally-configure-it-in-the-right-way-4e94c8e7e5c1

They all advocate using ```exclude: 'node_modules'```. This can be right or wrong, but it doesn't matter. I expect the average developer to use that kind of setup. Furthermore doing otherwise would be deliberately slowing down the (already slow) build process.

We already support this common scenario shipping ES5 as default. Developers can import from the es2018/es2015 folder and get the best possible performance for their environment. It is not a secret, it is **written in the readme**.

@hugomrdias the fundamental problem is in developer expectations. The dev community is moving in the direction of not transpiling, but as of now most of modules are still es5 :man_shrugging: 
I already tried to clarify that in the doc. I don't know what else to do.
You mentioned a few times having a es5 for unpkg. A PR would be most welcome!

### About my considerations on building instead of transpiling
In the current situation iter-tools can't depend on any es2015+ module. Because this won't be transpiled, and I would get a broken es5 version. Bundling would solve that problem. But this is not a problem for now.

### What now
I don't see any change getting much consensus. So, for now I would close. Everyone agree? @conartist6 @hugomrdias
