### ISSUE TITLE
Speed up native types

### ISSUE THREAD

**Issue by sithmel** [sithmel/iter-tools#92]
There is a good opportunity to speed up some of the functions, when they are a native type (array string, TypedArray).
For example:
```js
import ensureIterable from './internal/ensure-iterable'

export default function size (iterable) {
  if (typeof iterable === 'string') return iterable.length
  let size = 0
  // eslint-disable-next-line
  for (const _ of ensureIterable(iterable)) {
    size++
  }
  return size
}
```
There is an important caveat though. It is important to decide a cut-off point based on the size of the data structure: It can be a nice improvement using **array.prototype.map** whenever the size of the array is not big. But it can blow up the memory otherwise.

**Comment by KSXGitHub** [comment]
It might make sense in some functions such as `map` and `reduce`, but not in some other functions such as `size`.

Regarding `size`, I never use `itertools.size()` for strings, `Array`s, `Map`s and `Set`s simply because I can just access `.length`/`.size`, this means that I only use `itertools.size()` to count elements of iterables that I have no way to know its size (which is a bad design that I want to avoid). Now, even if you implement a shortcut for `size` to make it access `.length`/`.size` directly, I would still prefer not to use it as I would like to avoid overhead.

> It can be a nice improvement using **array.prototype.map** whenever the size of the array is not big. But it can blow up the memory otherwise.

To make matters worse, `array.map` ignores undefined value in a holey array (e.g. `[2, , , 3]`) whereas iterator protocol (such as `for ... of`,  `Array.from`) does not.

**Comment by sithmel** [comment]
About "size": I think it would be nice to remove the check from your code and just do that in the lib. The overhead should be minimal.

"map", "filter" etc. are more tricky.

My intention is to start experimenting around this optimisation after we have available a proper benchmarking suite https://github.com/sithmel/iter-tools/issues/89 

Thanks for pointing the different behaviour for sparse arrays, I didn't consider it in the first place!

**Comment by KSXGitHub** [comment]
Regarding the sparse array earlier, `Array.from` (and/or spread operator (`[...arr]`)) should be about to fix the problem. `Array.from` should also be used on typed arrays (`Int8Array`, `Int16Array`, etc.) if we were to call `.map()` because despite typed arrays don't have holes, their map functions never returns array of other types.

As for `.filter()` on typed arrays, you can call it directly without cloning.

**Comment by sithmel** [comment]
This looks interesting: https://github.com/codemix/fast.js

**Comment by conartist6** [comment]
> While fast.js may have been an improvement years ago, I doubt that it still is. JavaScript engines are always changing.

It's easy enough to find out, just check out the repo and run their perf benchmark. The fundamental logic of it is still sound.

I would however be wary of diverging from iterator behavior in iter-tools. Incidentally Sequins data structures do the fast.js thing -- this `List` type is non-sparse, and thus uses index-based loops for iteration. I guess I should be remembering that that is an additional selling point for the library.

**Comment by conartist6** [comment]
Hang on I'm being more confusing than helpful. I've just gone to the trouble of actually checking and the Array iterator is in fact non-sparse, which means that it will be even faster than fast.js as long as the implementation of it is native.

My test:
```js
const a = [0]
a[2] = 2

Object.values(a) // [0, 2]
Array.from(a) // [0, undefined, 2]
```

In the es5 version though we could still attain a speedup by special-casing arrays.

**Comment by KSXGitHub** [comment]
> ```javascript
> for (let i = 0, len = arrayLike.length; i < len; i++)
> ```

What about `for ... of ...`? It should eliminate the need for array index and access array element directly, make iteration even faster, it is also compatible with `Set` and `Map`.

> ```javascript
> return out
> ```

Should have been `return itertools.iterable(out)`, so that benchmark would be more accurate.

> ```javascript
> if ('length' in iterable)
> ```

Not all objects use `.length` as element counter (e.g. a dict that contains key `'length'`). You should use `Array.isArray()` instead. You should also support string, Map and Set.

**Comment by KSXGitHub** [comment]
> But is consistently slower

Hmm, did you compile your code to es5? (compiling your code to es5 will convert `for...of...` to calling `.next()`). In theory, `for...of...` (without babel) should be the most ideal in the latest V8 engine.

> An array is already an iterable, no need to call

But not an interator. Beside, the change should be transparent and yield no additional properties/methods.

> I can try to support Maps/Sets and use the size property. But that would require some extra benchmark.

You can use `for...of...`, or you can convert them to arrays using `Array.from`.

> I am checking the existence of the "length" property, because it covers in a single check:
> 
> * arrays
> * typedArrays
> * array like (arguments, NodeLists)
> * strings

`Array.isArray()` should cover the first 3, `typeof` should cover string.

You may want to support user-defined array-like objects, but by doing this, you essentially impose a limit upon user-defined iterables, forcing `.length` to be used in a specific way, this would also make the public API more complicated, not to mention custom array-like objects would not benefit from JavaScript engines' shortcut the same way native types do.

> * can the "length" be misleading? A custom iterable object can have a length property with a different meaning

Even in native types, `.length` is not element count, for instance:

```javascript
// encoding: UTF-8
'😄'.length // === 2
Array.from('😄').length // === 1
```

Even if you ignore edge cases, if a user want to use `.length` as element count for an iterable, they also have to do extra work of implementing random access via indexes, otherwise it won't work with `itertools.map()` even though they already implement `[Symbol.iterator]`.

**Comment by KSXGitHub** [comment]
**Another thing to note:** JavaScript is mostly run on the web where network latency greatly outweigh execution speed. This improvement would add an `if`-branch that handles native types and thus increase file size.

I prefer native types to be handled separately, outside of `map`, outside of even `iter-tools`, it should be in a separate package (such as `array-iter-tools`, `string-iter-tools`). This would enable developer to aggressively optimize for these specific use cases and allow user to choose using them should they want high-performant execution over fast download speed.

**Comment by sithmel** [comment]
>> did you compile your code to es5?
no

>> But not an iterator
No need to call **iterable**. Have a look at the function, this has already the correct interface

>> You can use for...of..., or you can convert them to arrays using Array.from.

"Array.from" consumes an iterable calling ".next", just like the "for .. of" loop. It is faster to just return the iterable

>> You may want to support user-defined array-like objects, but by doing this, you essentially impose a limit upon user-defined iterables, forcing .length to be used in a certain way. 

Exactly! I am changing that.

>> This "optimization" would add an if-branch to handle native types and thus increase file size.

It is a matter of trade offs. Hopefully that should only be a handful of bytes, for twice the speed in some cases. So probably still worth it

**Comment by KSXGitHub** [comment]
@sithmel 

> > You may want to support user-defined array-like objects, but by doing this, you essentially impose a limit upon user-defined iterables, forcing .length to be used in a certain way.
> 
> Exactly! I am changing that.

Is this enough of a counter-argument?

> Even in native types, `.length` is not element count, for instance:
> 
> ```js
> // encoding: UTF-8
> '😄'.length // === 2
> Array.from('😄').length // === 1
> ```
> 
> Even if you ignore edge cases, if a user want to use `.length` as element count for an iterable, they also have to do extra work of implementing random access via indexes, otherwise it won't work with `itertools.map()` even though they already implement `[Symbol.iterator]`.

**Comment by sithmel** [comment]
> Is this enough of a counter-argument?

yes, I won't use length for strings

**Comment by KSXGitHub** [comment]
> > Is this enough of a counter-argument?
> 
> yes, I won't use length for strings

My point is:
1. Not all objects use `.length` as element count.
2. Having `.length` does not mean having indexes.

**Comment by sithmel** [comment]
Yes, also my tests are broken. So I don't know what I am bench marking ... hang on :-)

**Comment by KSXGitHub** [comment]
I forgot:

> > You can use for...of..., or you can convert them to arrays using Array.from.
> 
> "Array.from" consumes an iterable calling ".next", just like the "for .. of" loop. It is faster to just return the iterable

I was talking about `Map` and `Set` specifically:
  * I don't think `Map#get` is fast.
  * `Set` don't have random access.

**Comment by sithmel** [comment]
Now that I fixed the tests, I am experiencing what @KSXGitHub is saying all along: "for .. of" is fast enough on a recent enough V8 (I am using node 10). So my "optimisations" are not making any difference.

Still I don't understand why iter-tools is so much slower than array methods!

**Comment by sithmel** [comment]
I think I understand now. My benchmarks were unfair. I was comparing this:
```js
  a.map(power2)
```
with
```js
  const iter = map(power2)
  Array.from(iter(a))
```
So eventually everything was converted to an array. But an array of course didn't need to be converted, so it was an unfair advantage.
I am now changed the benchmarks like this:
```js
  Array.from(a.map(power2))
```
with
```js
  const iter = map(power2)
  Array.from(iter(a))
```
WIth these results:
```
  map 1000 items
    ✓  Array map 1000 items x 8,622 ops/sec ±1.11% (90 runs sampled)
    ✓  iter-tools map 1000 items x 6,829 ops/sec ±0.29% (95 runs sampled)

    Result: iter-tools map 1000 items is 20.8% slower than Array map 1000 items.

  map 100000 items
    ✓  Array map 100000 items x 41.53 ops/sec ±0.95% (55 runs sampled)
    ✓  iter-tools map 100000 items x 63.56 ops/sec ±0.43% (65 runs sampled)

    Result: iter-tools map 100000 items is 53.02% faster than Array map 100000 items.
```

**Comment by KSXGitHub** [comment]
> ```js
> Array.from(a.map(power2))
> ```

Still unfair, you're converting an array to an array using native `Array.from`, V8 has a shortcut for this. I suggest:

```javascript
// I guess iter.toArray() does not invoke Array.from()
// but create array manually,
// it should be unbiased

iter.toArray(a.map(power2))

// vs

const iter = map(power2)
iter.toArray(iter(a))
```

**Comment by sithmel** [comment]
Eventually, I added only this simple optimisation:
```js
import ensureIterable from './internal/ensure-iterable'

const TypedArray = Object.getPrototypeOf(Int8Array)

export default function size (iterable) {
  if (Array.isArray(iterable)) return iterable.length
  if (iterable instanceof Map || iterable instanceof Set) return iterable.size
  if (Object.getPrototypeOf(iterable) === TypedArray) return iterable.length
  let size = 0
  // eslint-disable-next-line
  for (const _ of ensureIterable(iterable)) {
    size++
  }
  return size
}
```

I think I can close this ticket.

Waiting in case of objections ....

**Comment by KSXGitHub** [comment]
> ```javascript
> Object.getPrototypeOf(iterable) === TypedArray
> ```

What about `instanceof`:

```javascript
iterable instanceof TypedArray
```

**Comment by sithmel** [comment]
I am going to rename it to ```TypedArrayProto```. It is explained here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray#Description
